### ISSUE TITLE
Parcelable instead of Serializable

### ISSUE THREAD

**Issue by ghost** [filippella/Retrofit2-RestApiDemo#3]
I read that Parcelable is preferred method for Android instead of Serializable. I'm talking about Flower.java Pojo file.

`public class Flower implements Serializable ...`

I don't know if it makes much difference, but I have implemented it for exercise because I'm still learning. Should I make a pull request? I'm asking because then code won't be the same as in your tutorial. Is this a problem?

Thank you a lot for your tutorial, I have learnt a lot from it. :)

**Comment by filippoengidashet** [comment]
No problem at all, you can create a pull request for that. You are right it
is actually recommended to use parcelable because is lightweight like json.
As far as the code works I'm happy to make the improvement in the code.
Thanks for the collaboration on the code :)

**Comment by filippoengidashet** [comment]
And don't forget to follow me on github, I will follow you

**Comment by ghost** [comment]
OK! I will submit a few pull requests, because I need to learn about Git + GitHub. So please be patient with me, this is still new for me. Thanks!

**Comment by filippoengidashet** [comment]
no worries, it is a good practice doing this. Take your time

**Comment by ghost** [comment]
In my local fork I have removed the database so my implementation of Parcelable produces some conflicts with your database. Probably not worth it to change since Serializable works fine in your example. I will close this issue, maybe I will implement it later.
